#!/bin/python
'''
Please do not edit this file. This file is used to setup the default data for the application.
This file is used to create the default device template, patient template, registration code template,
device, registration code, usage session, patient view and patient list.
'''
from utils import find_device_template, create_device_template, \
    find_patient_template, update_patient_template, find_usage_type_template_by_parent_id, \
        find_registration_code_template, create_organization_registraion_code, \
            create_device_with_templateId, portal_builder_simulation_usage_session, \
                portal_builder_patient_view, portal_builder_patient_list,\
                      delete_default_device_template, create_defaul_caregiver, DEFAULT_DEVICE_TEMPLATE_NAME

def main():
    print('********************************************************************************')
    deviceTemplateSearchResult = find_device_template(DEFAULT_DEVICE_TEMPLATE_NAME.lower())
    if deviceTemplateSearchResult == None:
        print(">> The device template not exists.")
        deviceTemplateSearchResult = create_device_template()
    
    patientTemplate = find_patient_template()
    if patientTemplate == None:
        print('>> Patient template not found')
        return
    update_patient_template(patientTemplate)

    monitoringTemplate = find_usage_type_template_by_parent_id(deviceTemplateSearchResult['id'])
    if monitoringTemplate == None:
        print('>> Monitoring template not found')
        return

    registrationCodeTemplate = find_registration_code_template()
    if registrationCodeTemplate == None:
        print('>> Registration code template not found')
        return
    registrationCode = create_organization_registraion_code(registrationCodeTemplate['id'])
    if registrationCode == None:
        print('>> Registration code aready exists')
        return
    create_device_with_templateId(deviceTemplateSearchResult['id'], registrationCode['_id'])
    portal_builder_simulation_usage_session()
    portal_builder_patient_view()
    portal_builder_patient_list()
    delete_default_device_template()
    create_defaul_caregiver()

if __name__ == "__main__":
    main()